(function(root){
'use strict';
const P=typeof module!=='undefined'?require('./log-plot'):root.LogPlot,e=P.escape,f=P.format,colors=['#3559d9','#d17a22','#168675','#9465bf'];
function draw(series,{title,xLabel,yLabel,categories=null}){const W=940,H=360,l=86,r=28,t=38,b=58,valid=series.flatMap(s=>s.points.filter(Boolean));if(!valid.length)throw new Error('没有可绘制的数据。');let xmin=Infinity,xmax=-Infinity,ymin=Infinity,ymax=-Infinity;for(const p of valid){xmin=Math.min(xmin,p.x);xmax=Math.max(xmax,p.x);ymin=Math.min(ymin,p.y);ymax=Math.max(ymax,p.y)}if(categories){xmin=-.5;xmax=categories.length-.5;ymin=0}if(xmin===xmax){xmin-=.5;xmax+=.5}const pad=(ymax-ymin)*.1||Math.max(.1,Math.abs(ymin)*.02);ymin-=categories?0:pad;ymax+=pad;if(![xmin,xmax,ymin,ymax,xmax-xmin,ymax-ymin].every(Number.isFinite))throw new Error('数据跨度过大，无法绘图。');const X=x=>l+(x-xmin)/(xmax-xmin)*(W-l-r),Y=y=>H-b-(y-ymin)/(ymax-ymin)*(H-t-b);
const out=[`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" role="img" aria-label="${e(title)}" style="font:12px Segoe UI,Microsoft YaHei,sans-serif;background:white"><title>${e(title)}</title><rect width="${W}" height="${H}" fill="white"/>`];for(let i=0;i<=5;i++){const y=ymin+(ymax-ymin)*i/5;out.push(`<path d="M${l} ${Y(y)}H${W-r}" stroke="#e4eaf3"/><text x="${l-10}" y="${Y(y)+4}" text-anchor="end" fill="#5c708d">${e(f(y))}</text>`);if(!categories){const x=xmin+(xmax-xmin)*i/5;out.push(`<text x="${X(x)}" y="${H-b+24}" text-anchor="middle" fill="#5c708d">${e(f(x))}</text>`)}}
out.push(`<path d="M${l} ${t}V${H-b}H${W-r}" fill="none" stroke="#bdcbdc"/><text x="${l}" y="22" fill="#5c708d">${e(yLabel)}</text><text x="${W/2}" y="${H-9}" text-anchor="middle" fill="#5c708d">${e(xLabel)}</text>`);
series.forEach((s,i)=>{let chunk=[];function flush(){if(!chunk.length)return;if(chunk.length===1)out.push(`<circle cx="${X(chunk[0].x)}" cy="${Y(chunk[0].y)}" r="${categories?6:3}" fill="${colors[i]}"><title>${e(s.name+': '+f(chunk[0].y))}</title></circle>`);else out.push(`<path d="${chunk.map((p,j)=>(j?'L':'M')+X(p.x).toFixed(2)+' '+Y(p.y).toFixed(2)).join(' ')}" fill="none" stroke="${colors[i]}" stroke-width="1.8" stroke-linejoin="round"/>`);chunk=[]}for(const p of s.points){if(p)chunk.push(p);else flush()}flush();if(categories){const p=s.points[0];out.push(`<text x="${X(i)}" y="${H-b+25}" text-anchor="middle" fill="${colors[i]}">${e(categories[i])}</text><text x="${X(i)}" y="${Y(p.y)-14}" text-anchor="middle" fill="${colors[i]}">${e(f(p.y))}</text>`)}});out.push('</svg>');return out.join('')}
function log(r){if(!r.log.canOverlay)return '';return draw(r.log.rows.map(x=>({name:x.letter+' '+x.name,points:x.points})),{title:r.settings.metric+' · 多组日志对比',xLabel:r.settings.axis+' / '+(r.settings.axis==='Time'?({lj:'τ',real:'fs',metal:'ps'}[r.log.rows[0].units]||'原日志单位'):'步'),yLabel:r.settings.metric+' / '+r.log.rows[0].unitLabel})}
function heat(r){if(!r.heat.canPlot)return '';return draw(r.heat.rows.map((x,i)=>({name:x.letter+' '+x.name,points:[{x:i,y:x.kappa}]})),{title:'各自保存时间窗的约化热导率',xLabel:'实验标签 · 不是独立重复平均',yLabel:'κ* · LJ 约化热导率',categories:r.heat.rows.map(x=>x.letter)})}
const api={draw,log,heat,colors};if(typeof module!=='undefined')module.exports=api;else root.ComparePlot=api;
})(typeof window!=='undefined'?window:globalThis);
