(function(root){
'use strict';
const node=typeof module!=='undefined',E=node?require('./experiment-core'):root.ExperimentCore,L=node?require('./log-core'):root.LogCore,H=node?require('./heat-core'):root.HeatCore;
const MAX_BYTES=64*1024*1024,letters=['A','B','C','D'];
const need=(ok,s)=>{if(!ok)throw new Error(s)};
const numeric=/^[+-]?(?:\d+\.?\d*|\.\d+)(?:e[+-]?\d+)?$/i;
const labels={bx:'X 边界',by:'Y 边界',bz:'Z 边界',pair:'非键势',bond:'键势',epsilonAA:'AA ε',epsilonAB:'AB ε',epsilonBB:'BB ε',sigmaAA:'AA σ',sigmaAB:'AB σ',sigmaBB:'BB σ',cutoff:'LJ 截断倍数',k:'FENE K',rmax:'FENE R₀',bondEpsilon:'键内 ε',bondSigma:'键内 σ',harmonicK:'谐键 K',r0:'谐键 r₀',dt:'时间步长',temperature:'目标温度',seed:'速度随机种子',tdamp:'温控阻尼',pdamp:'压控阻尼',pressure:'目标压力',minimize:'最小化',npt:'启用 NPT',nvtSteps:'NVT 步数',nptSteps:'NPT 步数',settleSteps:'NVE 预运行步数',direction:'传热方向',bins:'分层数',exchange:'交换间隔',swaps:'每次交换数',warmSteps:'梯度建立步数',productionSteps:'正式采样步数',sampleEvery:'Nevery',sampleRepeat:'Nrepeat',thermoEvery:'thermo 间隔',dumpEvery:'dump 间隔',importUnitsConfirmed:'导入单位核对',mode:'流程',units:'单位'};
function canonical(v){if(typeof v==='string'&&numeric.test(v)&&Number.isFinite(Number(v)))return Number(v);return v}
function equal(a,b){return JSON.stringify(canonical(a))===JSON.stringify(canonical(b))}
function range(s,axis){const i=s.columns.indexOf(axis),xs=s.rows.filter(r=>r.values&&r.values[i]!==null).map(r=>r.values[i]);if(i<0||!xs.length)return {from:'',to:''};return {from:String(xs[0]),to:String(xs.at(-1))}}
function compact(d){const c={...d};if(c.version===2)c.trajectory=null;return c}
function checkSize(docs){need(docs.length>=2&&docs.length<=4,'请选择 2～4 个已保存实验。');let size=0;for(const d of docs){size+=new TextEncoder().encode(JSON.stringify(compact(d))).length;need(size<=MAX_BYTES,'对比内容总计最多 64 MB（不含轨迹）；请先缩短日志或分析文件。')}return size}
function inputSummary(d){const m=d.project.state.structure.model,count=new Map(),types=new Map();for(const a of m.atoms){count.set(a.mol,(count.get(a.mol)||0)+1);types.set(a.type,(types.get(a.type)||0)+1)}const sizes=new Map();for(const [mol,n] of count)if(mol!==0)sizes.set(n,(sizes.get(n)||0)+1);return {atoms:m.atoms.length,bonds:m.bonds.length,molecules:[...count.keys()].filter(x=>x!==0).length,unassigned:count.get(0)||0,chainSizes:[...sizes].sort((a,b)=>a[0]-b[0]).map(([n,c])=>n+' 粒子 × '+c+' 标签').join('；')||'无非零 mol 标签',types:[...types].sort((a,b)=>a[0]-b[0]).map(([t,n])=>t+': '+n).join('；'),masses:m.masses.map(a=>a.id+': '+a.mass).join('；'),box:m.box.map(b=>b.join(' ～ ')).join('；'),source:m.source,dirty:d.project.state.structure.dirty,mode:d.project.state.simulation.mode,units:'lj',...d.project.state.simulation.fields}}
function parameterRows(items){const rows=[],push=(group,key,label,values)=>rows.push({group,key,label,values,different:values.some(v=>!equal(v,values[0]))});
 for(const [key,label] of Object.entries({atoms:'粒子数',bonds:'键数',molecules:'非零 mol 标签数',unassigned:'mol=0 粒子数',chainSizes:'每个 mol 的粒子数分布',types:'type: 粒子数',masses:'type: 质量',box:'初始盒边界 X / Y / Z',source:'结构来源',dirty:'生成器有未应用修改',...labels}))push('保存的结构 / in 草稿',key,label,items.map(x=>x.input[key]??null));
 for(const key of ['atoms','bonds',...Object.keys(labels).filter(k=>k!=='importUnitsConfirmed')])push('原运行 parameters.json',key,({atoms:'运行粒子数',bonds:'运行键数'}[key]||labels[key]),items.map(x=>x.source?(key==='atoms'||key==='bonds'?x.source[key]:x.source.parameters[key])??null:null));
 return rows;
}
function heatResult(d){if(!d.heat)return {error:'未保存热导率结果。'};try{const h=d.heat,r=H.analyze(H.profile(h.raws[0]),H.energy(h.raws[1]),h.p);return {names:h.names,sourceName:h.source?.name||null,params:r.p,kappa:r.kappa,valid:r.valid,sd:r.variation?.sd??null,blocks:r.blocks,chunks:r.chunks,area:r.area,length:r.length,flux:r.flux,gradient:r.gradient,left:r.left,right:r.right,timeFrom:r.timeFrom,timeTo:r.timeTo,n:r.n,bins:r.bins,warnings:r.warnings,error:r.valid?null:'温度梯度或热流条件无效，未报告 κ*。'}}catch(err){return {error:err.message}}}
function prepare(docs){checkSize(docs);const seen=new Set();const items=docs.map((original,i)=>{const d=compact(original);E.validate(d);const key=d.experiment.id+'@'+d.experiment.revision;need(!seen.has(key),'不能重复选择同一实验版本。');seen.add(key);const input=inputSummary(d),source=d.heat?.source?JSON.parse(d.heat.source.raw):null;return {doc:d,key,letter:letters[i],name:d.project.project.name||'未命名实验',input,source,log:d.log?L.parse(d.log.raw):null,heat:heatResult(d)}});return items}
function metadata(items){const warnings=['输入表是保存时的草稿，不自动认定为结果的实际运行条件；参数相同也不证明来源相同。'];for(let i=0;i<items.length;i++){const a=items[i];if(!a.source)warnings.push(a.letter+' 未附原运行 parameters.json；请核对原 in 和结果来源。');else{const changed=Object.keys(labels).filter(k=>Object.hasOwn(a.source.parameters,k)&&!equal(a.input[k],a.source.parameters[k]));if(a.input.atoms!==a.source.atoms)changed.push('atoms');if(a.input.bonds!==a.source.bonds)changed.push('bonds');if(changed.length)warnings.push(a.letter+' 保存的输入与原运行记录不同：'+changed.map(k=>labels[k]||k).join('、')+'。')}
 for(let j=0;j<i;j++){const b=items[j];if(JSON.stringify(a.doc.project.state.structure.model)!==JSON.stringify(b.doc.project.state.structure.model))warnings.push(b.letter+' / '+a.letter+' 的完整结构（坐标、类型、质量或键连接）不同；表中粒子数相同也不代表模型相同。');if(a.doc.log&&b.doc.log&&a.doc.log.raw===b.doc.log.raw)warnings.push(b.letter+' / '+a.letter+' 使用相同日志原文，不能当作独立重复。');if(a.doc.heat&&b.doc.heat&&a.doc.heat.raws.every((r,k)=>r===b.doc.heat.raws[k]))warnings.push(b.letter+' / '+a.letter+' 使用相同热导率原始文件；不同时间窗也不是独立重复。');if(a.doc.experiment.id===b.doc.experiment.id)warnings.push(b.letter+' / '+a.letter+' 是同一实验的不同保存版本。')}}
 return {warnings,parameters:parameterRows(items),items:items.map(a=>({letter:a.letter,name:a.name,id:a.doc.experiment.id,revision:a.doc.experiment.revision,savedAt:a.doc.savedAt,notes:a.doc.project.project.notes,logName:a.doc.log?.fileName||null,sourceName:a.doc.heat?.source?.name||null,heat:a.heat,logView:a.doc.log?.view||null,segments:a.log?.segments.map(s=>({id:s.id,label:s.label,columns:s.columns,units:s.units,norm:s.norm,ended:s.ended,startLine:s.startLine,endLine:s.endLine,ranges:Object.fromEntries(s.columns.filter(k=>['step','time'].includes(k.toLowerCase())).map(k=>[k,range(s,k)]))}))||[]}))};
}
function defaults(meta){const rows=meta.items.map(x=>{const s=x.segments[x.logView?.segment??0];return {segment:s?.id??-1,from:x.logView?.axis==='Step'?x.logView.from:s?.ranges.Step?.from??'',to:x.logView?.axis==='Step'?x.logView.to:s?.ranges.Step?.to??''}});return {metric:'Temp',axis:'Step',rows,logConfirmed:false,heatConfirmed:false}}
// Keep original coordinates; thinning only changes the displayed path, never statistics or CSV.
function thin(points,limit=1400){if(points.length<=limit)return points;const out=[],stride=Math.ceil(points.length/(limit/5));for(let i=0;i<points.length;i+=stride){const bucket=points.slice(i,i+stride),valid=bucket.filter(Boolean);if(!valid.length){out.push(null);continue}let lo=valid[0],hi=valid[0];for(const p of valid){if(p.y<lo.y)lo=p;if(p.y>hi.y)hi=p}const wanted=new Set([valid[0],lo,hi,valid.at(-1)]);if(bucket.some(p=>p===null)){out.push(null);for(const p of valid)if(wanted.has(p))out.push(p,null)}else for(const p of valid)if(wanted.has(p))out.push(p)}return out}
function logs(items,settings){need(settings&&typeof settings.metric==='string'&&typeof settings.axis==='string'&&Array.isArray(settings.rows)&&settings.rows.length===items.length,'对比设置不完整。');need(['Step','Time'].includes(settings.axis),'横轴仅支持 Step 或 Time。');const rows=items.map((a,i)=>{const v=settings.rows[i],s=a.log?.segments[v.segment];const base={letter:a.letter,name:a.name};try{need(s,'未保存可用日志阶段。');need(typeof v.from==='string'&&typeof v.to==='string'&&numeric.test(v.from)&&numeric.test(v.to)&&Number.isFinite(Number(v.from))&&Number.isFinite(Number(v.to)),'请填写起止范围；空白草稿不参与计算。');const units=a.doc.log.view?.units==='auto'?s.units:a.doc.log.view?.units||'unknown';const result=L.series(s,settings.metric,settings.axis,Number(v.from),Number(v.to));return {...base,segment:v.segment,stage:s.label,command:s.command,ended:s.ended,units,norm:s.norm,unitLabel:L.unit(settings.metric,units,s.norm),startLine:s.startLine,endLine:s.endLine,range:[Number(v.from),Number(v.to)],stats:result.stats,points:result.points,issueCount:a.log.issueCount,errorCount:a.log.errorCount,issues:a.log.issues};}catch(err){return {...base,error:err.message}}});
 const reasons=[],warnings=[];if(rows.some(r=>r.error))reasons.push('每组选定阶段都需有有效的列和区间。');else{if(rows.some(r=>!['lj','real','metal'].includes(r.units)))reasons.push('至少一组日志单位未知；先在第 03 页核对并保存单位标签。');if(new Set(rows.map(r=>r.units)).size>1)reasons.push('日志单位体系不同，不能直接叠图，本页不换算单位。');const intensive=['Temp','Press','Density','Volume','Atoms','Step','Time','CPU'].includes(settings.metric);if(!intensive&&(rows.some(r=>!['yes','no'].includes(r.norm))||new Set(rows.map(r=>r.norm)).size>1))reasons.push('能量或自定义列的 norm 未知或不一致，不能直接叠图。');if(new Set(rows.map(r=>r.stage)).size>1)warnings.push('选中的运行阶段名称不同，请核对比较目的。');if(new Set(rows.map(r=>r.range.join(':'))).size>1)warnings.push('各组统计区间不同；均值差可能来自取样时间窗。');if(rows.some(r=>r.errorCount))warnings.push('至少一份日志含运行或非有限值错误；有效曲线仅用于排查。');if(rows.some(r=>!r.ended))warnings.push('至少一段未见 Loop time 结束标记。');if(settings.axis==='Step')warnings.push('Step 是步数；不同时间步长的同一步数不代表相同物理时长。')}
 if(settings.logConfirmed!==true)reasons.push('叠图前请核对各列物理含义、归一化、取样阶段及 LJ 参考尺度。');return {rows,reasons,warnings,canOverlay:reasons.length===0};
}
function heat(items,confirmed){const rows=items.map(a=>({letter:a.letter,name:a.name,...a.heat})),reasons=[],warnings=[];if(rows.some(r=>r.error||!r.valid))reasons.push('每组都需有已核对、有效的热导率分析；错误或未完成草稿不会作为零值。');if(confirmed!==true)reasons.push('绘图前请核对各组使用相同 LJ 参考尺度，并理解传热方向、尺寸和采样条件的差异。');const valid=rows.filter(r=>r.valid&&!r.error);if(new Set(valid.map(r=>r.params.direction)).size>1)warnings.push('传热方向不同，不能把方向差异解释成单一参数效应。');if(new Set(valid.map(r=>r.params.from+':'+r.params.to)).size>1)warnings.push('热导率采用各自保存的时间窗，没有统一截取。');if(new Set(valid.map(r=>r.length+':'+r.area)).size>1)warnings.push('实际采样盒尺寸不同，请检查尺寸效应。');warnings.push('不计算跨实验平均值、排名或置信区间；时间块 SD 不是均值误差。');return {rows,reasons,warnings,canPlot:reasons.length===0}}
function analyze(items,settings){return {settings:structuredClone(settings),log:logs(items,settings),heat:heat(items,settings.heatConfirmed)}}
function publicResult(r){return {...r,log:{...r.log,rows:r.log.rows.map(x=>({...x,points:x.points?thin(x.points):undefined}))}}}
function csvCell(v){if(v===null||v===undefined)return '""';let s=String(v);if(typeof v==='string'&&/^[\s]*[=+\-@]|^[\t\r\n]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"'}
function csv(rows){return '\uFEFF'+rows.map(r=>r.map(csvCell).join(',')).join('\r\n')+'\r\n'}
function report(meta,r){const logRows=r.log.rows.map(({points,...row})=>row);return {format:'lammps-experiment-comparison-report',version:1,createdAt:new Date().toISOString(),sources:meta.items.map(({segments,logView,heat,...item})=>item),parameters:meta.parameters,warnings:meta.warnings,settings:r.settings,log:{...r.log,rows:logRows},heat:r.heat,notes:['对比的是选中版本的已保存快照，不包含页面尚未保存的修改。','报告不是完整实验备份，也不能作为独立重复或物理收敛证明。','日志统计使用全部有效原记录，图中可抽样；无插值、无重新归零、无单位转换。','日志样本 SD 与热导率时间块 SD 均不是标准误或置信区间。']}}
function files(meta,r){const rep=report(meta,r),table=[['group','parameter',...meta.items.map(a=>a.letter+' '+a.name),'different'],...meta.parameters.map(p=>[p.group,p.label,...p.values,p.different])],stat=[['letter','name','id','revision','metric','units','norm','stage','from','to','n','mean','sample_SD','slope','error'],...r.log.rows.map((x,i)=>[x.letter,x.name,meta.items[i].id,meta.items[i].revision,r.settings.metric,x.units,x.norm,x.stage,x.stats?.start,x.stats?.end,x.stats?.n,x.stats?.mean,x.stats?.sd,x.stats?.slope,x.error])],points=[['letter','name','id','revision','source_line',r.settings.axis,r.settings.metric,'units','norm'],...r.log.rows.flatMap((x,i)=>(x.points||[]).filter(Boolean).map(p=>[x.letter,x.name,meta.items[i].id,meta.items[i].revision,p.line,p.x,p.y,x.units,x.norm]))],heats=[['letter','name','id','revision','direction','from','to','kappa_reduced','time_block_SD','length','area','left_R2','right_R2','valid','error'],...r.heat.rows.map((x,i)=>[x.letter,x.name,meta.items[i].id,meta.items[i].revision,x.params?.direction,x.params?.from,x.params?.to,x.kappa,x.sd,x.length,x.area,x.left?.r2,x.right?.r2,x.valid===true,x.error])];return {'comparison-report.json':JSON.stringify(rep,null,2)+'\n','parameters.csv':csv(table),'log-statistics.csv':csv(stat),'log-points.csv':csv(points),'heat-statistics.csv':csv(heats),'README.txt':['多组实验对比报告',...rep.notes,'日志：'+r.settings.metric+' / '+r.settings.axis,'日志叠图状态：'+(r.log.canOverlay?'已人工核对':'未启用；'+r.log.reasons.join('；')),'热导率绘图状态：'+(r.heat.canPlot?'已人工核对':'未启用；'+r.heat.reasons.join('；')),...meta.items.map(x=>x.letter+' '+x.name+' / '+x.id+' / r'+x.revision+' / '+x.savedAt),...meta.warnings,...r.log.warnings,...r.heat.warnings,'每组详细诊断、拟合条件和来源在 comparison-report.json 中。','CSV 空单元格表示缺失或无法计算，不表示零。','参考：https://docs.lammps.org/thermo_modify.html','参考：https://docs.lammps.org/units.html'].join('\n')+'\n'}}
const api={MAX_BYTES,compact,checkSize,prepare,metadata,defaults,range,parameterRows,logs,heat,analyze,publicResult,thin,files,report};if(node)module.exports=api;else root.CompareCore=api;
})(typeof window!=='undefined'?window:globalThis);
