(() => {
'use strict';
const C=CompareCore,T=ExperimentStore,$=id=>document.getElementById(id),e=LogPlot.escape,f=LogPlot.format;
let db=null,heads=[],meta=null,settings=null,result=null,worker=null,sequence=0,analysisSequence=0,loading=false,stale=true,logSvg='',heatSvg='',requests=new Map();
const button=document.createElement('button');button.id='openComparison';button.textContent='多组结果对比';document.querySelector('.experiment-tools').append(button);
const dialog=document.createElement('dialog');dialog.id='comparisonDialog';dialog.setAttribute('aria-labelledby','comparisonTitle');dialog.innerHTML=`<div class="comparison-heading"><div><span class="eyebrow">实验比较</span><h2 id="comparisonTitle">把不同运行，放在一起看。</h2><p>选择 2～4 个已保存实验，核对条件，再比较结果。</p></div><button id="closeComparison">关闭对比</button></div>
<div class="comparison-layout"><aside class="comparison-sources"><h3>选择实验</h3><p class="subtle">读取保存版本，不包含页面尚未保存的修改。打开对比不会切换或覆盖当前实验。</p><button id="refreshComparison">刷新本机记录</button><p id="comparisonCount" role="status"></p><div id="comparisonList"></div><button id="loadComparison" class="primary wide" disabled>载入选中实验</button><p class="subtle">要加入其他电脑的结果，先关闭此窗口，用顶部“打开实验文件”导入完整实验。</p></aside>
<div class="comparison-results"><p id="comparisonBusy" role="status"></p><p id="comparisonError" class="error error-box" role="alert" hidden></p><p id="comparisonStale" class="comparison-note" hidden>选择或本机列表已改变。下方仍是上次载入的快照，请重新载入后导出。</p><div id="comparisonEmpty" class="comparison-empty"><strong>先选择要比较的实验</strong><p>可以观察体系尺寸、相互作用参数或采样长度改变之后，曲线和结果有何差异。至少保存两组完整实验；同一文件的副本不会变成独立重复。</p></div>
<div id="comparisonLoaded" hidden><div id="comparisonLegend" class="comparison-legend"></div><details class="comparison-note" open><summary>比较前，先看来源与差异</summary><ul id="comparisonWarnings"></ul></details>
<section class="comparison-section"><h3>01 · 参数对照</h3><p class="subtle">高亮表示数值或记录不同，不表示错误。mol 标签的粒子数分布不自动证明化学链结构；原运行记录缺失显示“未记录”。</p><label class="check"><input id="comparisonOnlyDiff" type="checkbox" checked>只看不同项</label><div id="comparisonParameters" class="comparison-table" tabindex="0" aria-label="可横向滚动的参数对照表"></div></section>
<section class="comparison-section"><h3>02 · 日志曲线与统计</h3><div class="comparison-picks"><label>共同参数<select id="comparisonMetric"></select></label><label>共同横轴<select id="comparisonAxis"></select></label><button id="comparisonOverlap">使用各组范围的交集</button></div><div id="comparisonRanges" class="comparison-ranges"></div><label class="check comparison-confirm"><input id="comparisonLogConfirmed" type="checkbox">我已核对各列物理含义、归一化及阶段可比；LJ 数据使用同一参考尺度。</label><div id="comparisonLogNotes" class="comparison-note"></div><div id="comparisonLogChart" class="comparison-chart"></div><div id="comparisonLogStats" class="comparison-table" tabindex="0" aria-label="日志统计表"></div><p class="subtle">各曲线保留原 Step / Time，不插值、不归零、不换算单位。图形可能抽样，统计和 CSV 使用全部有效记录。SD 描述样本波动，不是均值误差。</p><details><summary>逐组运行与解析提示</summary><div id="comparisonLogDiagnostics"></div></details></section>
<section class="comparison-section"><h3>03 · 热导率结果</h3><p class="subtle">按各实验保存的分析条件重新计算。未核对、无效梯度或缺少结果时保留原因，不填零。修改分析区间请返回第 05 页并保存实验。</p><label class="check comparison-confirm"><input id="comparisonHeatConfirmed" type="checkbox">我已核对各组使用相同 LJ 参考尺度，并理解方向、尺寸、模型和采样条件的差异。</label><div id="comparisonHeatNotes" class="comparison-note"></div><div id="comparisonHeatChart" class="comparison-chart"></div><div id="comparisonHeatStats" class="comparison-table" tabindex="0" aria-label="热导率对照表"></div><details><summary>逐组拟合条件与诊断</summary><div id="comparisonHeatDiagnostics"></div></details></section>
<div class="comparison-export"><button id="comparisonDownload" class="primary" disabled>下载对比报告 ZIP</button><button id="comparisonReport" disabled>查看报告 / 复制文本</button><p class="subtle">包含参数与统计 CSV、日志有效原始点、已核对图表和带来源的 JSON 报告。对比选择与区间不自动保存；报告不能作为完整实验重新导入。</p></div>
<details class="comparison-help"><summary>范围与使用说明</summary><p>一次对比 2～4 组，所需内容总计最多 64 MB，不载入轨迹。只读取本机实验库；不运行 LAMMPS，不把副本或相邻时间窗当作独立重复，不自动计算跨实验平均值或收敛结论。</p><p>改变阶段、参数或区间后，需要重新核对日志可比性。能量及自定义列的 norm 未知或不同、单位未知或不同，均不叠图。其他参数差异会保留并提示，由你结合实验目的判断。报告导出不会修改源实验。</p><p><a href="https://docs.lammps.org/thermo_modify.html" target="_blank" rel="noopener">LAMMPS 归一化说明</a> · <a href="https://docs.lammps.org/units.html" target="_blank" rel="noopener">单位与 LJ 参考尺度</a></p></details>
</div></div></div>`;document.body.append(dialog);
const preview=document.createElement('dialog');preview.id='comparisonReportDialog';preview.innerHTML='<h2>对比报告文本</h2><p>这是含来源、条件、统计和诊断的报告；完整实验请另行备份。</p><textarea id="comparisonReportText" readonly rows="16" aria-label="对比报告 JSON"></textarea><div class="dialog-actions"><button id="comparisonCopy">复制 JSON</button><button id="comparisonReportClose">关闭报告</button></div>';document.body.append(preview);
function error(err){$('comparisonError').hidden=!err;$('comparisonError').textContent=err?.message||''}
function controls(){const count=dialog.querySelectorAll('[data-compare-id]:checked').length;$('comparisonCount').textContent='已选 '+count+' / 4 组';$('loadComparison').disabled=loading||count<2||count>4;$('refreshComparison').disabled=loading;for(const x of dialog.querySelectorAll('[data-compare-id]'))x.disabled=loading;$('comparisonStale').hidden=!meta||!stale;for(const id of ['comparisonDownload','comparisonReport'])$(id).disabled=loading||stale||!result}
function workerCall(action,args={}){if(!worker){worker=new Worker('compare-worker.js?v=compare3');worker.onmessage=ev=>{const p=requests.get(ev.data.id);if(!p)return;requests.delete(ev.data.id);ev.data.error?p.reject(new Error(ev.data.error)):p.resolve(ev.data.value)};worker.onerror=()=>{for(const p of requests.values())p.reject(new Error('对比读取进程失败，请重新载入；请使用本地 HTTP 网址。'));requests.clear();worker.terminate();worker=null;result=null;stale=true;controls()}}const id=++sequence;return new Promise((resolve,reject)=>{requests.set(id,{resolve,reject});worker.postMessage({id,action,...args})})}
function selected(){return [...dialog.querySelectorAll('[data-compare-id]:checked')].map(x=>x.dataset.compareId)}
async function refresh(){const old=new Set(selected());loading=true;controls();error(null);try{db??=await T.open(window.indexedDB);heads=await T.list(db);$('comparisonList').innerHTML=heads.length?heads.map(h=>`<label class="comparison-record"><input type="checkbox" data-compare-id="${e(h.id)}"${old.has(h.id)?' checked':''}><span><strong>${e(h.name)}</strong><small>${e(h.id)} · r${h.revision}</small><small>${new Date(h.savedAt).toLocaleString('zh-CN')} · ${h.atoms} 粒子</small><small>${h.logName?'有日志':'无日志'} · ${h.heatNames.length?'有热导率文件':'无热导率文件'}</small></span></label>`).join(''):'<p>暂无已保存实验。先关闭此窗口，点击“保存完整实验到本机”。</p>';stale=true;analysisSequence++;}catch(err){error(err)}finally{loading=false;controls()}}
button.onclick=()=>{TrajectoryStudio.pause();dialog.showModal();if(!heads.length)refresh()};$('closeComparison').onclick=()=>dialog.close();$('refreshComparison').onclick=refresh;
$('comparisonList').onchange=ev=>{if(!ev.target.matches('[data-compare-id]'))return;if(selected().length>4){ev.target.checked=false;error(new Error('最多选择 4 个实验。'));return}stale=true;analysisSequence++;controls()};
function value(v){return v===null||v===undefined?'未记录':v===''?'空白草稿':typeof v==='boolean'?(v?'是':'否'):typeof v==='object'?JSON.stringify(v):String(v)}
function table(headers,rows){return '<table><thead><tr>'+headers.map(h=>'<th scope="col">'+e(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map((v,i)=>'<'+(i?'td':'th scope="row"')+'>'+e(value(v))+'</'+(i?'td':'th')+'>').join('')+'</tr>').join('')+'</tbody></table>'}
function parameters(){const groups=[...new Set(meta.parameters.map(p=>p.group))];$('comparisonParameters').innerHTML=groups.map(g=>{const rows=meta.parameters.filter(p=>p.group===g&&(!$('comparisonOnlyDiff').checked||p.different));return '<h4>'+e(g)+'</h4><table><thead><tr><th scope="col">参数</th>'+meta.items.map(a=>'<th scope="col">'+e(a.letter+' · '+a.name)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(p=>'<tr'+(p.different?' class="comparison-different"':'')+'><th scope="row">'+e(p.label)+'<small>'+e(p.key)+'</small></th>'+p.values.map(v=>'<td>'+e(value(v))+'</td>').join('')+'</tr>').join('')+'</tbody></table>'+(!rows.length?'<p>没有不同项。</p>':'')}).join('')}
function options(){const segments=meta.items.map((x,i)=>x.segments[settings.rows[i].segment]).filter(Boolean);const columns=segments.length?segments[0].columns.filter(c=>segments.every(s=>s.columns.includes(c))):[];const metrics=columns.filter(c=>!['step','time'].includes(c.toLowerCase())),axes=['Step','Time'].filter(c=>columns.includes(c));if(!metrics.includes(settings.metric))settings.metric=metrics.includes('Temp')?'Temp':metrics[0]||'';if(!axes.includes(settings.axis))settings.axis=axes[0]||'Step';$('comparisonMetric').innerHTML=metrics.map(c=>`<option value="${e(c)}">${e(c)}</option>`).join('');$('comparisonMetric').value=settings.metric;$('comparisonAxis').innerHTML=axes.map(c=>`<option>${c}</option>`).join('');$('comparisonAxis').value=settings.axis;$('comparisonMetric').disabled=!metrics.length;$('comparisonAxis').disabled=!axes.length}
function fullRange(i){const s=meta.items[i].segments[settings.rows[i].segment],r=s?.ranges[settings.axis]||{from:'',to:''};Object.assign(settings.rows[i],r)}
function ranges(){ $('comparisonRanges').innerHTML=meta.items.map((a,i)=>`<div class="comparison-range"><strong>${e(a.letter+' · '+a.name)}</strong><label>运行阶段<select data-range="segment" data-index="${i}"${a.segments.length?'':' disabled'}>${a.segments.length?a.segments.map(s=>`<option value="${s.id}"${settings.rows[i].segment===s.id?' selected':''}>${s.id+1} · ${e(s.label)} · L${s.startLine}–${s.endLine}</option>`).join(''):'<option>没有可用日志</option>'}</select></label><div class="field-pair"><label>起点<input type="number" step="any" data-range="from" data-index="${i}" value="${e(settings.rows[i].from)}"></label><label>终点<input type="number" step="any" data-range="to" data-index="${i}" value="${e(settings.rows[i].to)}"></label></div><button data-full-range="${i}">该段全区间</button></div>`).join('')}
function unconfirm(){settings.logConfirmed=false;$('comparisonLogConfirmed').checked=false}
function notes(id,parts){$(id).innerHTML='<ul>'+parts.map(p=>'<li>'+e(p)+'</li>').join('')+'</ul>'}
function render(){parameters();notes('comparisonLogNotes',[...result.log.reasons,...result.log.warnings]);notes('comparisonHeatNotes',[...result.heat.reasons,...result.heat.warnings]);logSvg=heatSvg='';try{logSvg=ComparePlot.log(result);heatSvg=ComparePlot.heat(result)}catch(err){error(err)}$('comparisonLogChart').innerHTML=logSvg;$('comparisonHeatChart').innerHTML=heatSvg;
 $('comparisonLogStats').innerHTML=table(['组','阶段 / 单位 / norm','有效范围','点数','均值','样本 SD','斜率','状态'],result.log.rows.map(x=>[x.letter,x.error?'—':x.stage+' / '+x.units+' / '+x.norm,x.stats?x.stats.start+' ～ '+x.stats.end:'—',x.stats?.n??'—',f(x.stats?.mean),f(x.stats?.sd),f(x.stats?.slope),x.error||'已计算；未自动判断平衡']));
 $('comparisonLogDiagnostics').innerHTML=result.log.rows.map(x=>'<h4>'+e(x.letter+' · '+x.name)+'</h4><p>'+e(x.error||'命令：'+(x.command||'未识别')+'；原文 L'+x.startLine+'–'+x.endLine+'；解析提示 '+x.issueCount+' 条，以下最多显示 10 条。')+'</p><ul>'+(x.issues||[]).slice(0,10).map(v=>'<li>'+e('L'+v.line+' '+v.message)+'</li>').join('')+'</ul>').join('');
 $('comparisonHeatStats').innerHTML=table(['组','方向','Step 区间','κ*','时间块 SD','采样盒 L* / A*','两侧 R²','状态'],result.heat.rows.map(x=>[x.letter,x.params?.direction??'—',x.params?x.params.from+' ～ '+x.params.to:'—',f(x.kappa),f(x.sd),x.length?f(x.length)+' / '+f(x.area):'—',x.left?f(x.left.r2)+' / '+f(x.right.r2):'—',x.error||'有效估计；仍需收敛检查']));
 $('comparisonHeatDiagnostics').innerHTML=result.heat.rows.map(x=>'<h4>'+e(x.letter+' · '+x.name)+'</h4><p>'+e(x.error||'原文件：'+x.names.join(' + ')+'；参数来源：'+(x.sourceName||'未记录')+'；拟合层：'+x.params.leftFrom+'–'+x.params.leftTo+' / '+x.params.rightFrom+'–'+x.params.rightTo+'；Nevery/Nrepeat='+x.params.every+'/'+x.params.repeat+'；有效时间块 '+x.chunks.filter(c=>c.valid).length+'/'+x.chunks.length)+'</p><ul>'+(x.warnings||[]).map(w=>'<li>'+e(w)+'</li>').join('')+'</ul>').join('');
}
async function calculate(){if(!settings)return;const token=++analysisSequence;result=null;controls();$('comparisonBusy').textContent='正在计算对比…';error(null);$('comparisonLogChart').innerHTML='';$('comparisonHeatChart').innerHTML='';try{const next=await workerCall('analyze',{settings});if(token!==analysisSequence)return;result=next;render()}catch(err){if(token===analysisSequence)error(err)}finally{if(token===analysisSequence){$('comparisonBusy').textContent='';controls()}}}
$('loadComparison').onclick=async()=>{loading=true;controls();error(null);$('comparisonBusy').textContent='正在读取已保存实验…';try{const ids=selected(),docs=[];for(const id of ids){const d=await T.get(db,id),h=heads.find(x=>x.id===id);if(!d||d.experiment.revision!==h.revision)throw new Error('某个实验已更新，请刷新本机记录后重新载入。');docs.push(C.compact(d))}C.checkSize(docs);const next=await workerCall('load',{docs});meta=next;settings=C.defaults(meta);options();meta.items.forEach((x,i)=>{if(x.logView?.axis===settings.axis){settings.rows[i].from=x.logView.from;settings.rows[i].to=x.logView.to}else fullRange(i)});stale=false;$('comparisonEmpty').hidden=true;$('comparisonLoaded').hidden=false;$('comparisonLegend').innerHTML=meta.items.map((x,i)=>`<div style="--series:${ComparePlot.colors[i]}"><strong>${e(x.letter+' · '+x.name)}</strong><small>${e(x.id)} · r${x.revision}</small><small>保存于 ${new Date(x.savedAt).toLocaleString('zh-CN')}</small></div>`).join('');$('comparisonWarnings').innerHTML=meta.warnings.map(w=>'<li>'+e(w)+'</li>').join('');$('comparisonLogConfirmed').checked=false;$('comparisonHeatConfirmed').checked=false;ranges();dialog.scrollTop=0;await calculate()}catch(err){error(err)}finally{loading=false;$('comparisonBusy').textContent='';controls()}};
$('comparisonOnlyDiff').onchange=()=>meta&&parameters();
$('comparisonRanges').onchange=ev=>{if(ev.target.dataset.range!=='segment')return;const i=Number(ev.target.dataset.index);settings.rows[i].segment=Number(ev.target.value);const old=settings.axis;options();if(old!==settings.axis)settings.rows.forEach((_,j)=>fullRange(j));else fullRange(i);ranges();unconfirm();calculate()};
$('comparisonRanges').oninput=ev=>{const k=ev.target.dataset.range;if(!['from','to'].includes(k))return;settings.rows[Number(ev.target.dataset.index)][k]=ev.target.value;unconfirm();calculate()};
$('comparisonRanges').onclick=ev=>{const b=ev.target.closest('[data-full-range]');if(!b)return;fullRange(Number(b.dataset.fullRange));ranges();unconfirm();calculate()};
$('comparisonMetric').onchange=ev=>{settings.metric=ev.target.value;unconfirm();calculate()};$('comparisonAxis').onchange=ev=>{settings.axis=ev.target.value;settings.rows.forEach((_,i)=>fullRange(i));ranges();unconfirm();calculate()};
$('comparisonOverlap').onclick=()=>{try{if(settings.rows.some(r=>r.from===''||r.to===''||!Number.isFinite(Number(r.from))||!Number.isFinite(Number(r.to))))throw new Error('请先填写各组有效范围。');const from=Math.max(...settings.rows.map(r=>Number(r.from))),to=Math.min(...settings.rows.map(r=>Number(r.to)));if(from>to)throw new Error('当前范围没有交集，原区间保持不变。');for(const r of settings.rows){r.from=String(from);r.to=String(to)}ranges();unconfirm();calculate()}catch(err){error(err)}};
for(const [id,key] of [['comparisonLogConfirmed','logConfirmed'],['comparisonHeatConfirmed','heatConfirmed']])$(id).onchange=ev=>{settings[key]=ev.target.checked;calculate()};
async function exported(){if(stale||!result||loading)throw new Error('请重新载入并等待对比完成。');const token=analysisSequence,logImage=logSvg,heatImage=heatSvg,out=await workerCall('export');if(token!==analysisSequence||stale||loading)throw new Error('对比条件已改变，请等待计算完成后重新导出。');if(logImage)out.files['log-comparison.svg']=logImage;if(heatImage)out.files['heat-comparison.svg']=heatImage;return out}
$('comparisonDownload').onclick=async()=>{try{const out=await exported(),url=URL.createObjectURL(new Blob([InCore.zip(out.files)],{type:'application/zip'})),a=document.createElement('a');a.href=url;a.download='lammps-comparison.zip';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);$('comparisonBusy').textContent='已发起报告下载，请确认文件已保存；也可查看并复制报告文本。'}catch(err){error(err)}};
$('comparisonReport').onclick=async()=>{try{const out=await exported();$('comparisonReportText').value=JSON.stringify(out.report,null,2);preview.showModal()}catch(err){error(err)}};
$('comparisonReportClose').onclick=()=>preview.close();$('comparisonCopy').onclick=async()=>{try{await navigator.clipboard.writeText($('comparisonReportText').value);StructureStudio.toast('已复制对比报告 JSON。')}catch{$('comparisonReportText').focus();$('comparisonReportText').select()}};
})();
