(() => {
'use strict';
const G=window.GuideCore,$=id=>document.getElementById(id),key='lammps-learning-guide-v1';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let storage=null,state,storageMessage='学习进度只记录在当前浏览器，与完整实验文件分开。';
try{storage=window.localStorage;state=G.normalize(storage.getItem(key))}catch{state=G.normalize(null);storageMessage='浏览器未开放本机存储；学习进度仅在本页有效。'}
const quick=document.createElement('button');quick.id='guideQuickAccess';quick.type='button';quick.textContent='学习指引';document.querySelector('.toolbar').prepend(quick);
const panel=document.createElement('section');panel.id='learningGuide';panel.className='panel guide-panel';panel.setAttribute('aria-labelledby','guideTitle');
panel.innerHTML=`<div class="guide-head"><div><span class="eyebrow">贯穿全流程 · 学习路线</span><h2 id="guideTitle">亲手完成一次 LAMMPS 模拟</h2><p>按实际流程学习：结构 → 输入 → 作业 → 日志 → 热导率 → 轨迹 → 比较。</p></div><div class="guide-head-actions"><span id="guideProgress" role="status"></span><button id="guideToggle" type="button" aria-expanded="true" aria-controls="guideBody">收起指引</button></div></div><div id="guideBody"><p class="guide-caution">页码沿网站建立顺序；学习路线按运行顺序。站内示例用于练习，完成知识自测不代表已运行超算或验证研究结果。</p><div id="guideRoute" class="guide-route" role="group" aria-label="学习步骤"></div><div class="guide-content"><div class="guide-lesson"><span id="guideFile" class="guide-file"></span><h3 id="guideStepTitle"></h3><dl><div><dt>这一步要懂</dt><dd id="guideGoal"></dd></div><div><dt>现在动手</dt><dd id="guidePractice"></dd></div><div><dt>如何检查</dt><dd id="guideEvidence"></dd></div><div><dt>用于课题时</dt><dd id="guideReal"></dd></div></dl><div class="guide-lesson-actions"><button id="guideOpenPage" class="primary" type="button">进入操作页</button><a id="guideDoc" target="_blank" rel="noopener noreferrer">查看官方命令说明 ↗</a></div></div><div class="guide-check"><h3>用自己的话答一道题</h3><p id="guideQuestion"></p><div id="guideOptions" role="radiogroup" aria-label="学习自测选项"></div><p id="guideFeedback" role="status" aria-live="polite"></p><div class="guide-check-actions"><button id="guideLearned" type="button">标记为已练习</button><button id="guideClearAnswer" type="button">清除本题答案</button><button id="guideNext" type="button">下一步 →</button></div><small id="guideStorage"></small></div></div></div>`;
document.querySelector('.workflow-nav').after(panel);
const route=$('guideRoute');route.innerHTML=G.steps.map((s,i)=>`<button type="button" data-guide-step="${s.id}" aria-pressed="false"><span class="guide-number">${String(i+1).padStart(2,'0')}</span><span>${esc(s.title)}</span><span class="guide-done" aria-hidden="true"></span></button>`).join('');
function persist(){if(!storage)return;try{storage.setItem(key,JSON.stringify(state))}catch{storage=null;storageMessage='本机存储失败；学习进度仅在本页有效。'}}
function current(){return G.steps.find(s=>s.id===state.selected)||G.steps[0]}
function render(){const s=current(),i=G.steps.indexOf(s),answer=state.answers[s.id],grade=G.grade(s.id,answer),done=state.completed.includes(s.id);$('guideProgress').textContent=state.completed.length+' / '+G.steps.length+' 步自评已练习';quick.textContent='学习指引 · '+state.completed.length+'/'+G.steps.length;$('guideBody').hidden=!state.open;$('guideToggle').textContent=state.open?'收起指引':'展开指引';$('guideToggle').setAttribute('aria-expanded',String(state.open));
 for(const b of route.querySelectorAll('[data-guide-step]')){const id=b.dataset.guideStep,finished=state.completed.includes(id);b.setAttribute('aria-pressed',String(id===s.id));b.setAttribute('aria-label',G.steps.find(x=>x.id===id).title+'，'+(finished?'自评已练习':'尚未自评完成'));b.classList.toggle('is-done',finished);b.querySelector('.guide-done').textContent=finished?'✓':''}
 $('guideFile').textContent=s.file;$('guideStepTitle').textContent=(i+1)+' / '+G.steps.length+' · '+s.title;for(const [id,value] of [['guideGoal',s.goal],['guidePractice',s.practice],['guideEvidence',s.evidence],['guideReal',s.real],['guideQuestion',s.question]])$(id).textContent=value;
 $('guideDoc').href=s.doc;$('guideDoc').textContent=s.docLabel+' ↗';$('guideOptions').innerHTML=s.options.map((v,n)=>`<label class="guide-option"><input type="radio" name="guideAnswer" value="${n}"${answer===n?' checked':''}><span>${esc(v)}</span></label>`).join('');
 $('guideFeedback').textContent=grade===null?'先选择答案，再用操作结果核对自己的理解。':(grade?'回答正确。':'再想一想。')+s.explain;$('guideFeedback').dataset.result=grade===null?'none':grade?'correct':'incorrect';$('guideLearned').disabled=!done&&grade!==true;$('guideLearned').textContent=done?'取消“已练习”':'我已亲自操作并能解释';$('guideClearAnswer').disabled=answer===undefined;$('guideNext').textContent=i===G.steps.length-1?'回到第一步 ↺':'下一步：'+G.steps[i+1].title+' →';$('guideOpenPage').textContent=s.id==='compare'?'打开多组结果对比':'进入 '+s.title+' 页面';$('guideStorage').textContent=storageMessage;
}
function select(id){if(!G.steps.some(s=>s.id===id))return;state.selected=id;persist();render()}
function navigate(s){const target=$(s.page);if(!target)return;target.click();if(s.id!=='compare')$(s.id+'Workspace')?.scrollIntoView({block:'start',behavior:'smooth'})}
route.onclick=e=>{const b=e.target.closest('[data-guide-step]');if(b)select(b.dataset.guideStep)};
$('guideOptions').onchange=e=>{if(e.target.name!=='guideAnswer')return;const s=current(),n=Number(e.target.value);state.answers[s.id]=n;if(G.grade(s.id,n)!==true)state.completed=state.completed.filter(id=>id!==s.id);persist();render()};
$('guideLearned').onclick=()=>{const s=current();if(state.completed.includes(s.id))state.completed=state.completed.filter(id=>id!==s.id);else if(G.grade(s.id,state.answers[s.id])===true)state.completed.push(s.id);persist();render()};
$('guideClearAnswer').onclick=()=>{const id=current().id;delete state.answers[id];state.completed=state.completed.filter(x=>x!==id);persist();render()};
$('guideOpenPage').onclick=()=>navigate(current());$('guideNext').onclick=()=>{const index=G.steps.indexOf(current());const next=G.steps[(index+1)%G.steps.length];select(next.id);navigate(next)};
$('guideToggle').onclick=()=>{state.open=!state.open;persist();render()};quick.onclick=()=>{state.open=true;persist();render();panel.scrollIntoView({block:'start',behavior:'smooth'});$('guideToggle').focus()};
const nav=document.querySelector('.workflow-nav');nav.addEventListener('click',e=>{const button=e.target.closest('button');const step=G.steps.find(s=>s.page===button?.id);if(step)select(step.id)});
new MutationObserver(()=>{const active=G.steps.find(s=>s.id!=='compare'&&$(s.page)?.getAttribute('aria-pressed')==='true');if(active&&active.id!==state.selected&&(!$('comparisonDialog')?.open))select(active.id)}).observe(nav,{subtree:true,attributes:true,attributeFilter:['aria-pressed']});
const comparison=$('openComparison');comparison?.addEventListener('click',()=>select('compare'));$('comparisonDialog')?.addEventListener('close',()=>{const active=G.steps.find(s=>s.id!=='compare'&&$(s.page)?.getAttribute('aria-pressed')==='true');if(active)select(active.id)});
render();
})();
