(() => {
'use strict';
const steps=[
 {id:'structure',page:'structureStep',title:'认识结构 data',file:'model.data',goal:'说清粒子、分子标签、键与盒边界分别是什么。',practice:'保留 8 条链 × 每链 16 粒子的示例，点击“生成并替换当前结构”；核对 128 个粒子、120 条键，再打开“data 原文”。',evidence:'在 Masses、Atoms、Bonds 与盒边界中各找到一项；指出 mol 标签不是键。',real:'研究模型要另外核对链拓扑、组分和初始密度。规则直链只是初始构型。',question:'粒子坐标和链的键连接主要写在哪个文件？',options:['model.data','submit.sh','log.lammps'],correct:0,explain:'data 的 Atoms 记录粒子，Bonds 记录连接；in 决定如何计算，log 记录运行输出。',doc:'https://docs.lammps.org/read_data.html',docLabel:'LAMMPS data 格式'},
 {id:'input',page:'inputStep',title:'读懂模拟 in',file:'in.lammps',goal:'分清结构、力场、时间步和运行阶段的作用。',practice:'先选“读取与受力检查”，在脚本中找 units、read_data、pair_style / pair_coeff 与 run 0；再切换平衡和 RNEMD，观察新增的命令与输出。运行后可把 equilibrated.data 导回第 01 页，检查 Velocities，再在 RNEMD 页选择从已平衡结构开始。',evidence:'能指出使用的单位、A–B 相互作用参数、时间步以及每个 run 推进的步数；复用时能说明原速度是否保留、哪些平衡命令被跳过。',real:'本站仅生成 LJ 珠簧链教学输入。正式模型的势函数、参数和单位必须先有可靠来源；data 本身不证明已平衡。',question:'run 0 检查完成后，体系是否已经经历了动力学平衡？',options:['是，零步足以平衡','否，只做初始计算，不推进动力学时间','只要没有报错就是'],correct:1,explain:'run 0 可初始化并计算当前结构的能量等量，但没有推进时间，不能证明平衡。',doc:'https://docs.lammps.org/run.html',docLabel:'LAMMPS run 命令'},
 {id:'job',page:'jobStep',title:'准备超算作业',file:'submit.sh + 作业包',goal:'区分 LAMMPS 输入与学校调度器作业，知道在哪里找结果。',practice:'打开“超算与续算”，载入明确标注的 Slurm 教学示例，逐项读资源、启动命令、结果目录和检查点说明。',evidence:'能解释节点、MPI 进程、墙钟时限与模拟步数各指什么；说出提交后怎样查作业 ID 和日志。',real:'取得学校示例后，核对调度器、分区、模块、LAMMPS 命令与 MPI 启动方式，再在计算节点做短作业。网页不会替你登录或提交。',question:'10,000 个粒子的体系意味着必须申请 10,000 个 MPI 进程吗？',options:['必须','不必；进程数须用短作业测量并遵守平台要求','网页会自动决定'],correct:1,explain:'粒子数是模型规模，MPI 进程数是计算资源；合适的核数要根据平台和短作业测试确定。',doc:'https://docs.lammps.org/Run_basics.html',docLabel:'LAMMPS 运行基础'},
 {id:'analysis',page:'analysisStep',title:'读日志与判断运行',file:'log.lammps',goal:'先辨认报错、阶段和单位，再选正确的观察区间。',practice:'若暂无自己运行的结果，点击“载入教学日志”；选 NVT / NPT / RNEMD 段，切换 Temp、Density 或能量，查看原始行和区间统计。',evidence:'能找到 Step 起止、结束标记及警告；解释曲线波动与均值各说明什么。',real:'自己的日志要与实际 in、版本和作业目录对应。没有报错或曲线看似平稳，都不能单独证明物理平衡。',question:'温度曲线看起来平稳，可以单凭这一点判定体系已平衡吗？',options:['可以','不可以，还要看密度/构象、时长与初始状态等','只要 Step 足够大就可以'],correct:1,explain:'需要结合目标状态、密度、能量、链构象和独立初始条件检查；本站统计不自动判定平衡。',doc:'https://docs.lammps.org/Run_output.html',docLabel:'LAMMPS 输出文件'},
 {id:'heat',page:'heatStep',title:'从原始结果算热导率',file:'temperature.profile + heat_exchange.dat',goal:'把同一稳态时间窗的温度梯度和交换能量对应起来。',practice:'在“热导率分析”载入教学结果；核对来源，选区间与两侧拟合层，观察剖面、累计能量和拟合诊断。',evidence:'能指出两条传热路径、热流截面积、拟合梯度，以及报告中的 κ* 为什么仍是 LJ 约化量。',real:'改变盒尺寸、采样时长与初始构型做验证；时间块标准差不等于独立重复的均值误差。',question:'计算 RNEMD 热导率，能只用 thermo 温度均值吗？',options:['能','不能，还需同一区间的温度剖面和交换能量','只需要轨迹视频'],correct:1,explain:'热导率由热流与空间温度梯度得到；本站要求剖面和累计交换能量来自同一次运行并对应同一时间窗。',doc:'https://docs.lammps.org/Howto_kappa.html',docLabel:'LAMMPS 热导率方法'},
 {id:'trajectory',page:'trajectoryStep',title:'观察构象与轨迹',file:'production.lammpstrj',goal:'看懂粒子位置随 Step 的变化，并核对拓扑来源。',practice:'点击“载入真实教学轨迹”，逐帧查看链；再试试按 type / mol 着色、盒内显示与展开。',evidence:'能说明一帧的 Step 来自 dump，播放速度只改变观看速度；画键前要核对配套 data。',real:'构象图可以帮助发现异常与解释结构，但一段好看的动画不能证明模拟平衡或材料热导率。',question:'把网页播放速度从 2 帧/秒改为 20 帧/秒，会改变 LAMMPS 的物理时间步吗？',options:['会','不会，只改变观看速度','只改变热导率'],correct:1,explain:'帧的 Step 与坐标来自已生成的 dump；网页播放不会重新积分动力学。',doc:'https://docs.lammps.org/dump.html',docLabel:'LAMMPS dump 格式'},
 {id:'compare',page:'openComparison',title:'保存、比较与复述',file:'完整实验 + 对比报告',goal:'能追溯每份结果，并区分参数差异与独立重复。',practice:'先保存至少两份完整实验，再打开“多组结果对比”；核对参数、原运行记录、单位和来源后再叠图。',evidence:'能说出每组的模型、采样窗和来源；比较报告与完整实验备份各保存什么。',real:'同一运行的前半与后半是时间窗比较，不是两次独立模拟。结论还需要尺寸、时长和独立重复验证。',question:'同一次运行的全程与后半程，可以当成两次独立重复计算误差吗？',options:['可以','不可以，它们共享同一份原始轨迹','只要另存为副本就可以'],correct:1,explain:'不同时间窗和文件副本仍共享原始运行；独立重复应有独立初始状态或速度等明确的重复设计。',doc:'https://docs.lammps.org/units.html',docLabel:'LAMMPS 单位与比较'}
];
const ids=new Set(steps.map(s=>s.id));
function normalize(raw){let value=raw;try{if(typeof raw==='string')value=JSON.parse(raw)}catch{value=null}if(!value||typeof value!=='object'||Array.isArray(value))value={};const answers={};for(const s of steps){const n=value.answers?.[s.id];if(Number.isInteger(n)&&n>=0&&n<s.options.length)answers[s.id]=n}return {selected:ids.has(value.selected)?value.selected:steps[0].id,answers,completed:steps.filter(s=>Array.isArray(value.completed)&&value.completed.includes(s.id)&&answers[s.id]===s.correct).map(s=>s.id),open:value.open!==false}}
function grade(id,answer){const step=steps.find(s=>s.id===id);return !step||!Number.isInteger(answer)||answer<0||answer>=step.options.length?null:answer===step.correct}
const api={steps,normalize,grade};if(typeof module!=='undefined'&&module.exports)module.exports=api;if(typeof window!=='undefined')window.GuideCore=api;
})();
