(() => {
'use strict';
const H=HeatCore,$=id=>document.getElementById(id),e=LogPlot.escape,f=LogPlot.format;
let raw=null,names=null,pro=null,en=null,current=null,plots=null,source=null,serial=0,dragStart=null;
const ws=document.createElement('section');ws.id='heatWorkspace';ws.hidden=true;ws.setAttribute('aria-label','RNEMD 热导率分析');
const num=(id,title,hint='')=>'<label>'+title+'<input id="heat-'+id+'" type="number" step="1"><small>'+hint+'</small></label>';
const pair=(a,b)=>'<div class="field-pair">'+a+b+'</div>';
ws.innerHTML=`<div class="intro"><div><span class="eyebrow">传热计算 / 05</span><h1>从温度梯度，算到热导率。</h1><p>把同一次采样的两个文件放在一起，逐项看清计算依据。</p></div><span class="mode-tag">RNEMD · LJ 约化单位</span></div>
<div class="log-toolbar"><div><button id="heatImport" class="primary">导入两个结果文件</button><button id="heatDemo">载入教学结果</button><button id="heatOpen">打开分析记录</button></div><span id="heatBusy" role="status"></span><input id="heatFiles" type="file" multiple hidden accept=".profile,.dat,.txt"><input id="heatSession" type="file" hidden accept=".json"></div>
<p class="subtle log-save-note">选择 temperature.profile 与 heat_exchange.dat。分析仅在本机浏览器进行；刷新前请保存顶部“完整实验”，或单独下载分析记录。</p><p id="heatError" class="error error-box" role="alert" hidden></p>
<div id="heatEmpty" class="panel log-empty"><span class="log-empty-mark" aria-hidden="true">↗</span><h2>把模拟结果连成完整的计算过程</h2><p>温度剖面 → 两侧梯度；累计交换能量 → 热流；二者相除 → 热导率。先载入 128 粒子教学实跑结果即可练习。</p><small>本页分析已有输出，不启动 LAMMPS。教学短跑用于学习，不代表材料的收敛结果。</small></div>
<div id="heatLoaded" hidden><div class="panel log-file-summary"><div><strong id="heatNames"></strong><p id="heatInfo"></p></div><span>交换层自动排除</span></div>
<div class="heat-workspace"><aside class="panel heat-controls"><h2>选择计算依据</h2><form id="heatForm" novalidate>
<div class="section-label"><span>01</span> 核对输出设置</div><button id="heatParameters" type="button" class="wide">导入原运行 parameters.json</button><input id="heatParametersFile" type="file" accept=".json" hidden><p id="heatSource" class="subtle">可从该次作业包读取参数，也可以手动填写。</p><label>原模拟的单位<select id="heat-units"><option value="unknown">尚未核对</option><option value="lj">units lj · LJ 约化单位</option></select></label><label>实际传热方向<select id="heat-direction"><option value="x">x</option><option value="y">y</option><option value="z">z</option></select></label>
${pair(num('every','采样间隔 Nevery','从原 in 的 fix profile 核对。'),num('repeat','每块样本 Nrepeat','本版要求 Nfreq = Nevery × Nrepeat。'))}
<label class="check heat-confirm"><input id="heat-confirmed" type="checkbox"><span>已核对：两个文件来自同一连续生产段；周期双向传热、固定盒、norm sample ave one，温度为无约束三维 LJ 粒子的 v_bead_temp。</span></label><p class="subtle">这些设置不能从结果文件完整识别，请对照产生它们的 in 文件。不会套用当前编辑器参数。</p>
<div class="section-label"><span>02</span> 统一时间区间 / Step</div>${pair(num('from','起始步'),num('to','结束步'))}<div class="log-range-actions"><button type="button" id="heatAll">全部共同区间</button><button type="button" id="heatHalf">后半段</button></div><p class="subtle">起止步须为已有输出步；选择后半段不等于确认稳态。</p>
<div class="section-label"><span>03</span> 两侧拟合层号</div>${pair(num('leftFrom','左支首层'),num('leftTo','左支末层'))}${pair(num('rightFrom','右支首层'),num('rightTo','右支末层'))}<p id="heatBinHint" class="subtle"></p><label>点击层号或温度图中的点，将其设为<select id="heatLayerTarget"><option value="leftFrom">左支首层</option><option value="leftTo">左支末层</option><option value="rightFrom">右支首层</option><option value="rightTo">右支末层</option></select></label><div id="heatLayers" class="heat-layers" aria-label="选择拟合层号"></div><p id="heatPickHint" class="subtle" role="status"></p><div class="section-label"><span>04</span> 查看随时间的波动</div>${num('groups','时间块数','完整区间均分为这些连续块；每块至少含 2 次温度输出。')}
</form></aside>
<div class="heat-results"><div class="panel heat-selector"><h2>在能量图上拖选分析区间</h2><p class="subtle">蓝色区域是当前选择。松开后吸附到共同输出步，至少保留两个温度块；也可用滑块或左侧数字输入。</p><div id="heatTimeOverview" class="heat-time-overview"></div><div class="heat-sliders"><label>起始步滑块<input id="heatFromSlider" type="range" min="0" step="1"></label><label>结束步滑块<input id="heatToSlider" type="range" min="0" step="1"></label></div><p id="heatSelectionHint" class="subtle" role="status"></p></div><div id="heatValidation" aria-live="polite"></div><div id="heatResult" hidden><p id="heatWindow" class="heat-window"></p><div id="heatStats" class="log-statistics"></div>
<div class="panel log-chart-panel"><div class="panel-heading"><h2>温度剖面与两支拟合</h2><span class="subtle">蓝：左支 · 棕：右支 · 灰：排除</span></div><div class="heat-chart-scroll"><div id="heatTempChart"></div></div><p id="heatFits" class="log-trend-info"></p><p class="subtle">每层按输出块等权平均；误差棒为块间温度标准差，不是均值的不确定度。交换层及未选层不参与拟合。</p></div>
<div class="panel log-chart-panel"><div class="panel-heading"><h2>累计交换能量</h2><span class="subtle">蓝色虚线：自由截距线性拟合</span></div><div class="heat-chart-scroll"><div id="heatEnergyChart"></div></div><p id="heatFlux" class="log-trend-info"></p></div>
<div class="panel heat-detail"><h2>把计算过程展开</h2><div id="heatMath" class="heat-math"></div><p>周期方向有两条传热路径，因此 J* = (dQ*/dt*) / (2A*)。合并结果使用两支梯度幅度的平均值；不对左右热导率直接取平均。</p><p>κ* 为约化数值，不能直接标成 W/(m·K)。只有明确映射 σ、ε、m 后，才可用 κ = κ* k<sub>B</sub>/(σ·τ)，τ = σ√(m/ε) 转换。</p></div>
<div class="panel heat-detail"><h2>分块检查时间稳定性</h2><p id="heatVariation"></p><div class="log-table-scroll"><table><thead><tr><th>Step 区间</th><th>κ*</th><th>状态</th></tr></thead><tbody id="heatBlocks"></tbody></table></div><p class="subtle">标准差描述时间块之间的波动。尚未验证块的独立性，不作为标准误或置信区间；任一块无效时不汇总标准差。</p></div>
<div id="heatWarnings" class="note"></div></div>
<div class="panel heat-export"><button id="heatSave" disabled>下载分析记录 / 草稿 ↓</button><button id="heatExport" class="primary" disabled>下载报告与图表 ZIP ↗</button><p id="heatSaveHint" class="subtle">未完成或有错误的分析设置也能下载为草稿；保存草稿不代表计算通过。</p><p class="subtle">记录包含两份结果原文、参数来源与当前设置，可再次打开。ZIP 另含计算报告、分层/能量/时间块 CSV 和两张 SVG 图。也可通过顶部“完整实验”一起保存。</p></div>
</div></div></div>
<details class="panel log-help"><summary>文件要求、计算约定与学习顺序</summary><p>只支持本站 RNEMD 模板的两个输出：温度四列 Chunk / Coord1 / Ncount / v_bead_temp，能量五列 TimeStep / v_elapsed / f_exchange / v_cross_area / v_heat_length。各文件最大 25 MB、250,000 行。分层数、盒尺寸和时间步长须固定，缺块、重置、非有限值、非等宽分层会停止计算。</p><p>至少 8 层，去掉第 1 层（冷层）与第 N/2+1 层（热层）后，每支至少保留 3 层做普通最小二乘拟合。层数太少无法检查线性关系。本版不处理 ave running/window、非周期单向热流、真实单位或续算拼接。</p><p>先在日志页检查运行状态，再在本页比较多个后期时间窗和拟合区域。R² 高也不能单独证明稳态；还需更长采样、重复实验、交换强度与尺寸测试。</p><p><a href="https://docs.lammps.org/fix_thermal_conductivity.html" target="_blank" rel="noreferrer">LAMMPS RNEMD 与双向热流 ↗</a> · <a href="https://docs.lammps.org/fix_ave_chunk.html" target="_blank" rel="noreferrer">分层平均的定义 ↗</a> · <a href="https://docs.lammps.org/units.html" target="_blank" rel="noreferrer">LJ 单位 ↗</a></p></details>`;
document.querySelector('main footer').before(ws);
function show(){for(const prefix of ['structure','input','analysis','job','trajectory']){$(prefix+'Workspace').hidden=true;$(prefix+'Step').setAttribute('aria-pressed',false)}ws.hidden=false;$('heatStep').setAttribute('aria-pressed',true)}$('heatStep').onclick=show;
const keys=['units','direction','every','repeat','from','to','leftFrom','leftTo','rightFrom','rightTo','groups'];
function values(){return {...Object.fromEntries(keys.map(k=>[k,$('heat-'+k).value])),confirmed:$('heat-confirmed').checked}}
function restore(p){for(const k of keys)$('heat-'+k).value=p[k];$('heat-confirmed').checked=p.confirmed===true}
function error(err){$('heatError').textContent=err?err.message+' 原有分析保持不变。':'';$('heatError').hidden=!err}
function accept(texts,labels,p,nextSource=null){const nextPro=H.profile(texts[0]),nextEn=H.energy(texts[1]);if(p)H.draft(p);if(nextSource)H.parameters(nextSource.raw,nextPro,nextEn);pro=nextPro;en=nextEn;raw=texts;names=labels;source=nextSource;restore(p||H.defaults(pro,en));$('heatNames').textContent=names.join(' + ');$('heatInfo').textContent=pro.blocks.length+' 个温度块 · '+pro.n+' 层 · '+en.rows.length+' 个能量记录点';$('heatBinHint').textContent='第 1 与 '+(pro.n/2+1)+' 层为交换层，始终排除。每支至少选 3 层。';$('heatPickHint').textContent='先选要修改的端点，再点层号。';$('heatEmpty').hidden=true;$('heatLoaded').hidden=false;error(null);render()}
function selectors(){
 const p=values();$('heatTimeOverview').innerHTML='<div class="heat-overview-labels"><span>Q* · 全部记录</span><span>Step '+en.rows[0].step+'–'+en.rows.at(-1).step+'</span></div>'+HeatPlot.overview(en,p);
 for(const [id,key] of [['heatFromSlider','from'],['heatToSlider','to']]){let nearest=0;for(let i=1;i<en.rows.length;i++)if(Math.abs(en.rows[i].step-Number(p[key]))<Math.abs(en.rows[nearest].step-Number(p[key])))nearest=i;$(id).max=en.rows.length-1;$(id).value=nearest;$(id).setAttribute('aria-valuetext','Step '+en.rows[nearest].step)}
 $('heatSelectionHint').textContent='当前数字区间：Step '+(p.from||'未填')+'–'+(p.to||'未填')+'。滑块位置对齐最近输出步，精确值以数字输入为准。';
 const target=$('heatLayerTarget').value,left=target.startsWith('left');
 $('heatLayers').innerHTML=Array.from({length:pro.n},(_,i)=>{const id=i+1,exchange=id===1||id===pro.n/2+1,inBranch=left?id>=2&&id<=pro.n/2:id>=pro.n/2+2,active=(id>=Number(p.leftFrom)&&id<=Number(p.leftTo))||(id>=Number(p.rightFrom)&&id<=Number(p.rightTo));return '<button type="button" data-layer="'+id+'" aria-label="第 '+id+' 层'+(exchange?'，交换层':'')+'" aria-pressed="'+active+'"'+(exchange||!inBranch?' disabled':'')+'>'+id+'</button>'}).join('');
 let note='手动设置；尚未导入原运行的参数记录。';if(source){const imported=H.parameters(source.raw,pro,en),changed=['units','direction','every','repeat'].some(k=>String(imported[k])!==String(p[k]));note='来源：'+source.name+'。'+(changed?'当前设置已手动调整，请重新核对。':'分层数、粒子数、时间步长与输出间隔已匹配。')+'相同数值不能证明来自同一次运行，仍需核对文件来源和原 in。'}$('heatSource').textContent=note;
}
function render(){document.dispatchEvent(new Event('studiochange'));current=null;plots=null;$('heatSave').disabled=!raw;$('heatExport').disabled=true;$('heatResult').hidden=true;if(!raw)return;selectors();$('heatSaveHint').textContent='可以下载未完成的分析草稿；结果原文与当前输入会一并保留。';try{
 const r=H.analyze(pro,en,values());plots={temp:HeatPlot.render(r,'temperature'),energy:HeatPlot.render(r,'energy')};current=r;
 $('heatValidation').innerHTML='';$('heatResult').hidden=false;$('heatWindow').textContent='共同区间 Step '+r.p.from+'–'+r.p.to+' · '+r.blocks+' 个完整温度块 · t* '+f(r.timeFrom)+'–'+f(r.timeTo)+' · 首个实际温度样本 Step '+r.firstSample;
 const card=(label,value,note)=>'<div class="log-stat"><span>'+label+'</span><strong>'+e(value)+'</strong><small>'+note+'</small></div>';
 $('heatStats').innerHTML=card('约化热导率 κ*',r.valid?f(r.kappa):'未得出',r.valid?'当前区间的数值估计':'梯度或热流方向不满足')+card('热流密度 J*',f(r.flux),'ε / (τ·σ²)')+card('平均梯度幅度 g*',f(r.gradient),'两支 |dT*/ds*| 的平均')+card('时间块标准差',f(r.variation?.sd),'κ* 的时间波动；非置信区间');
 $('heatTempChart').innerHTML=HeatPlot.render(r,'temperature',{interactive:true});$('heatEnergyChart').innerHTML=plots.energy;
 $('heatFits').textContent='左支梯度 '+f(r.left.slope)+'，R² '+f(r.left.r2)+'；右支梯度 '+f(r.right.slope)+'，R² '+f(r.right.r2)+'。';
 $('heatFlux').textContent='dQ*/dt* = '+f(r.qfit.slope)+'，R² = '+f(r.qfit.r2)+'；截面积 A* = '+f(r.area)+'，传热长度 L* = '+f(r.length)+'。';
 $('heatMath').textContent='J* = '+f(r.qfit.slope)+' / (2 × '+f(r.area)+') = '+f(r.flux)+'\nκ* = J* / g* = '+(r.valid?f(r.flux)+' / '+f(r.gradient)+' = '+f(r.kappa):'暂不计算：需要左正、右负的温度梯度和正热流')+'\n分支估计：κ*左 = '+f(r.leftK)+'；κ*右 = '+f(r.rightK);
 $('heatVariation').textContent='有效时间块 '+r.chunks.filter(c=>c.valid).length+' / '+r.chunks.length+'；块间样本标准差：'+f(r.variation?.sd)+'。';$('heatBlocks').innerHTML=r.chunks.map(c=>'<tr><td>'+c.from+'–'+c.to+'</td><td>'+f(c.kappa)+'</td><td>'+(c.valid?'可估计':'无法有效估计')+'</td></tr>').join('');
 $('heatWarnings').innerHTML='<strong>怎样理解本次结果</strong><ul>'+r.warnings.map(w=>'<li>'+e(w)+'</li>').join('')+'</ul>';$('heatSaveHint').textContent='当前分析可保存并导出报告；科学有效性仍需结合结果提示判断。';$('heatExport').disabled=false;
 }catch(err){$('heatValidation').innerHTML='<div class="error error-box">'+e(err.message)+'</div>'}}
 $('heatForm').onsubmit=ev=>ev.preventDefault();function changed(ev){if(['heat-units','heat-direction','heat-every','heat-repeat'].includes(ev.target.id))$('heat-confirmed').checked=false;render()}$('heatForm').oninput=changed;$('heatForm').onchange=changed;
 function selectRange(a,b){try{const selected=H.snapRange(pro,en,a,b);$('heat-from').value=selected.from;$('heat-to').value=selected.to;render()}catch(err){$('heatSelectionHint').textContent=err.message}}
 for(const [id,key,other] of [['heatFromSlider','from','to'],['heatToSlider','to','from']])$(id).oninput=()=>{const chosen=en.rows[Number($(id).value)].step,old=Number($('heat-'+other).value);selectRange(chosen,Number.isFinite(old)&&$('heat-'+other).value!==''?old:chosen)};
 function pickLayer(id){const target=$('heatLayerTarget').value,left=target.startsWith('left'),lo=left?2:pro.n/2+2,hi=left?pro.n/2:pro.n;if(id<lo||id>hi){$('heatPickHint').textContent='请选择当前分支的非交换层（'+lo+'–'+hi+'）。';return}const p=values();p[target]=String(id);const a=Number(p[left?'leftFrom':'rightFrom']),b=Number(p[left?'leftTo':'rightTo']);if(b-a<2||a<lo||b>hi){$('heatPickHint').textContent='这次选择会使该支少于 3 层，请先调整另一端点。';return}$('heat-'+target).value=id;render();$('heatPickHint').textContent=({leftFrom:'左支首层',leftTo:'左支末层',rightFrom:'右支首层',rightTo:'右支末层'}[target])+'已设为第 '+id+' 层。'}
 for(const id of ['heatLayers','heatTempChart']){$(id).onclick=ev=>{const el=ev.target.closest('[data-layer]');if(el&&!el.disabled)pickLayer(Number(el.dataset.layer))};if(id==='heatTempChart')$(id).onkeydown=ev=>{if(['Enter',' '].includes(ev.key)){const el=ev.target.closest('[data-layer]');if(el){ev.preventDefault();pickLayer(Number(el.dataset.layer))}}}}
 const overview=$('heatTimeOverview');function pointerStep(ev){const rect=overview.querySelector('svg').getBoundingClientRect(),x=Math.max(68,Math.min(876,(ev.clientX-rect.left)/rect.width*900)),first=en.rows[0].step,last=en.rows.at(-1).step;return first+(x-68)/808*(last-first)}
 overview.onpointerdown=ev=>{if(ev.button!==0||!en||!ev.target.closest('svg'))return;ev.preventDefault();dragStart=pointerStep(ev);overview.setPointerCapture(ev.pointerId)};
 overview.onpointermove=ev=>{if(dragStart===null)return;const now=pointerStep(ev),first=en.rows[0].step,span=en.rows.at(-1).step-first,lo=Math.min(dragStart,now),hi=Math.max(dragStart,now),brush=$('heatBrush');brush.setAttribute('x',68+(lo-first)/span*808);brush.setAttribute('width',(hi-lo)/span*808);$('heatSelectionHint').textContent='拖选 Step '+Math.round(lo)+'–'+Math.round(hi)+'；松开后对齐输出步。'};
 overview.onpointerup=ev=>{if(dragStart===null)return;const start=dragStart,end=pointerStep(ev);dragStart=null;overview.releasePointerCapture(ev.pointerId);selectRange(start,end)};
 overview.onpointercancel=()=>{dragStart=null;selectors()};
 function range(half){if(!pro)return;const p=H.defaults(pro,en);if(half){const available=en.rows.filter(r=>r.step>=Number(p.from)&&r.step<=Number(p.to));p.from=String(available[Math.floor((available.length-1)/2)].step)}$('heat-from').value=p.from;$('heat-to').value=p.to;render()}
 $('heatAll').onclick=()=>range(false);$('heatHalf').onclick=()=>range(true);
 $('heatImport').onclick=()=>$('heatFiles').click();$('heatOpen').onclick=()=>$('heatSession').click();
 function busy(on){$('heatBusy').textContent=on?'正在读取结果…':'';for(const id of ['heatDemo','heatImport','heatOpen','heatParameters'])$(id).disabled=on}
 $('heatFiles').onchange=async ev=>{const fs=[...ev.target.files];ev.target.value='';if(!fs.length)return;const token=++serial;busy(true);try{if(fs.length!==2)throw new Error('请一次选择温度剖面与交换能量这两个文件。');if(fs.some(x=>x.size>25*1024*1024))throw new Error('单个文件最大 25 MB。');const texts=await Promise.all(fs.map(x=>x.text()));if(token!==serial)return;const i=texts.findIndex(x=>/^#\s*Chunk\s+Coord1/m.test(x));if(i<0)throw new Error('没有找到温度剖面文件。');accept([texts[i],texts[1-i]],[fs[i].name,fs[1-i].name])}catch(err){if(token===serial)error(err)}finally{if(token===serial)busy(false)}};
 $('heatSession').onchange=async ev=>{const file=ev.target.files[0];ev.target.value='';if(!file)return;const token=++serial;busy(true);try{if(file.size>60*1024*1024)throw new Error('分析记录最大 60 MB。');const o=H.readSession(await file.text());if(token===serial)accept(o.raws,o.names,o.p,o.source)}catch(err){if(token===serial)error(err)}finally{if(token===serial)busy(false)}};
 $('heatParameters').onclick=()=>$('heatParametersFile').click();$('heatParametersFile').onchange=async ev=>{const file=ev.target.files[0];ev.target.value='';if(!file||!pro)return;const token=++serial;busy(true);try{if(file.size>65536)throw new Error('参数记录最大 64 KB。');const text=await file.text(),p=H.parameters(text,pro,en);if(token!==serial)return;source={name:file.name,raw:text};restore({...values(),...p});error(null);render();StructureStudio.toast('已带入原运行参数，请核对来源与原 in 后勾选确认。')}catch(err){if(token===serial)error(err)}finally{if(token===serial)busy(false)}};
 $('heatDemo').onclick=async()=>{const token=++serial;busy(true);try{const paths=['teaching-temperature.profile','teaching-heat_exchange.dat'];const texts=await Promise.all(paths.map(async name=>{const resp=await fetch('samples/'+name);if(!resp.ok)throw new Error('教学结果加载失败。');return resp.text()}));if(token!==serial)return;const p=H.defaults(H.profile(texts[0]),H.energy(texts[1]));accept(texts,paths,{...p,units:'lj',direction:'z',every:'10',repeat:'20',confirmed:true});StructureStudio.toast('已载入独立 128 粒子实跑结果；输出设置已按该次 in 文件核对。')}catch(err){if(token===serial)error(err)}finally{if(token===serial)busy(false)}};
 function download(data,name,type){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);StructureStudio.toast('已发起下载 '+name+'，请在下载记录中确认。')}
 $('heatSave').onclick=()=>{if(raw)try{download(H.session(raw,names,values(),source),current?'rnemd-analysis.json':'rnemd-draft.json','application/json;charset=utf-8')}catch(err){error(err)}};
 $('heatExport').onclick=()=>{if(!current)return;const r=current;try{download(InCore.zip({'analysis.txt':H.report(r,names)+'参数来源：'+(source?source.name+'（原文见分析记录）':'手动填写或教学示例')+'\n' +$('heatSource').textContent+'\n','temperature.csv':H.csv(r),'energy.csv':'Step,time_reduced,Q_reduced,area_reduced,length_reduced\n'+r.rows.map(t=>[t.step,t.time,t.q,t.area,t.length].join(',')).join('\n')+'\n','time-blocks.csv':'from_step,to_step,kappa_reduced,valid\n'+r.chunks.map(c=>[c.from,c.to,c.kappa??'',c.valid].join(',')).join('\n')+'\n','temperature.svg':plots.temp,'energy.svg':plots.energy,'rnemd-analysis.json':H.session(raw,names,values(),source)}),'rnemd-report.zip','application/zip')}catch(err){error(err)}};
window.HeatStudio={capture(){return raw?JSON.parse(H.session(raw,names,values(),source)):null},restore(doc){const o=doc===null?null:H.readSession(JSON.stringify(doc));++serial;busy(false);dragStart=null;if(o){accept(o.raws,o.names,o.p,o.source);return}raw=null;names=null;pro=null;en=null;source=null;current=null;plots=null;$('heatEmpty').hidden=false;$('heatLoaded').hidden=true;$('heatError').hidden=true;$('heatSave').disabled=true;$('heatExport').disabled=true}};
})();
